#!/bin/sh

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export XDG_CURRENT_DESKTOP=niri
export _JAVA_AWT_WM_NONREPARENTING=1

/home/walter/.config/conky/conky.sh &

exec niri
