#!/bin/bash

# Muestra el historial del portapapeles en un menú para copiar y pegar

cliphist list | wmenu -l 20 -p " > " -f 'IosevkaTermSlab Nerd Font Propo 10' -S '#1793D0' -m '#8CC716' -M '#333333' -N '#333333' | cliphist decode | wl-copy
